name: dedalus
description: "Dedalus Mobile Application."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_launcher_icons: ^0.14.4
  get_storage: ^2.1.1
  http: ^1.4.0
  intl: ^0.20.2
  path: ^1.9.1
  sqflite: ^2.4.2
  table_calendar: ^3.2.0
  flutter_secure_storage: ^9.2.4

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/app_icon.png"
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/images/app_icon.png"
  windows:
    generate: true
    image_path: "assets/images/app_icon.png"
  macos:
    generate: true
    image_path: "assets/images/app_icon.png"
